default_agent: agentcore_multiagent
agents:
  agentcore_lang_runtime:
    name: agentcore_lang_runtime
    language: python
    node_version: '20'
    entrypoint: E:/AgentCore/01_agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: E:\AgentCore
    aws:
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-c980c3716d
      execution_role_auto_create: false
      account: '948360714466'
      region: ap-south-1
      ecr_repository: 948360714466.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-agentcore_lang_runtime
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_lang_runtime-CZEBhp6SVH
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:runtime/agentcore_lang_runtime-CZEBhp6SVH
      agent_session_id: 705c9d67-f616-4fae-a237-3bfffe76ab9b
    codebuild:
      project_name: bedrock-agentcore-agentcore_lang_runtime-builder
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-c980c3716d
      source_bucket: bedrock-agentcore-codebuild-sources-948360714466-ap-south-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_lang_runtime_mem-6C52kHDYTd
      memory_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:memory/agentcore_lang_runtime_mem-6C52kHDYTd
      memory_name: agentcore_lang_runtime_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agentcore_memory:
    name: agentcore_memory
    language: python
    node_version: '20'
    entrypoint: E:/AgentCore/02_agentcore_memory.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: E:\AgentCore
    aws:
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-c5d93b0882
      execution_role_auto_create: false
      account: '948360714466'
      region: ap-south-1
      ecr_repository: 948360714466.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-agentcore_memory
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_memory-0WHPMBDMv1
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:runtime/agentcore_memory-0WHPMBDMv1
      agent_session_id: f7c6b292-b57a-4ff7-bc33-20e99a21c487
    codebuild:
      project_name: bedrock-agentcore-agentcore_memory-builder
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-c5d93b0882
      source_bucket: bedrock-agentcore-codebuild-sources-948360714466-ap-south-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_myagent_memory-HPEmQF7XcU
      memory_arn: null
      memory_name: agentcore_memory_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agentcore_with_memory:
    name: agentcore_with_memory
    language: python
    node_version: '20'
    entrypoint: E:/AgentCore/02_agentcore_memory.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: E:\AgentCore
    aws:
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-7265038260
      execution_role_auto_create: false
      account: '948360714466'
      region: ap-south-1
      ecr_repository: 948360714466.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-agentcore_with_memory
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_with_memory-4GI6ID9Qik
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:runtime/agentcore_with_memory-4GI6ID9Qik
      agent_session_id: 12af7911-d380-4b18-8bda-a6406af8bfef
    codebuild:
      project_name: bedrock-agentcore-agentcore_with_memory-builder
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-7265038260
      source_bucket: bedrock-agentcore-codebuild-sources-948360714466-ap-south-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_myagent_memory-HPEmQF7XcU
      memory_arn: null
      memory_name: agentcore_with_memory_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agentcore_correct_memory:
    name: agentcore_correct_memory
    language: python
    node_version: '20'
    entrypoint: E:/AgentCore/02_agentcore_memory.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: E:\AgentCore
    aws:
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-6dbeb07d76
      execution_role_auto_create: false
      account: '948360714466'
      region: ap-south-1
      ecr_repository: 948360714466.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-agentcore_correct_memory
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_correct_memory-k9mNgWCtHq
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:runtime/agentcore_correct_memory-k9mNgWCtHq
      agent_session_id: 19c80167-ee2f-4daa-b9e3-464f73d051bf
    codebuild:
      project_name: bedrock-agentcore-agentcore_correct_memory-builder
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-6dbeb07d76
      source_bucket: bedrock-agentcore-codebuild-sources-948360714466-ap-south-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_myagent_memory-HPEmQF7XcU
      memory_arn: null
      memory_name: agentcore_correct_memory_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agentcore_multiagent:
    name: agentcore_multiagent
    language: python
    node_version: '20'
    entrypoint: E:/AgentCore/02_agentcore_memory.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: E:\AgentCore
    aws:
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-34eb85a7cd
      execution_role_auto_create: false
      account: '948360714466'
      region: ap-south-1
      ecr_repository: 948360714466.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-agentcore_multiagent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_multiagent-mNtHnu3n0q
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:runtime/agentcore_multiagent-mNtHnu3n0q
      agent_session_id: aba1ed93-3144-46bc-b301-0bf0c3c6d17c
    codebuild:
      project_name: bedrock-agentcore-agentcore_multiagent-builder
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-34eb85a7cd
      source_bucket: bedrock-agentcore-codebuild-sources-948360714466-ap-south-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_myagent_memory-HPEmQF7XcU
      memory_arn: null
      memory_name: agentcore_multiagent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
