default_agent: supervisor_agent_2
agents:
  search_agent:
    name: search_agent
    language: python
    node_version: '20'
    entrypoint: E:/AgentCore/agentcore_a2a/entrypoints/search_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: E:\AgentCore
    aws:
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-2899021ae0
      execution_role_auto_create: false
      account: '948360714466'
      region: ap-south-1
      ecr_repository: 948360714466.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-search_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: search_agent-xGABJYEJCA
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:runtime/search_agent-xGABJYEJCA
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-search_agent-builder
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-2899021ae0
      source_bucket: bedrock-agentcore-codebuild-sources-948360714466-ap-south-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: GROQ_API_KEY
    api_key_credential_provider_name: search_agent_groq_api_key
    is_generated_by_agentcore_create: false
  summary_agent:
    name: summary_agent
    language: python
    node_version: '20'
    entrypoint: E:/AgentCore/agentcore_a2a/entrypoints/summary_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: E:\AgentCore
    aws:
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-ad0d38ef06
      execution_role_auto_create: false
      account: '948360714466'
      region: ap-south-1
      ecr_repository: 948360714466.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-summary_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: summary_agent-hkQC5vDtik
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:runtime/summary_agent-hkQC5vDtik
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-summary_agent-builder
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-ad0d38ef06
      source_bucket: bedrock-agentcore-codebuild-sources-948360714466-ap-south-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: GROQ_API_KEY
    api_key_credential_provider_name: summary_agent_groq_api_key
    is_generated_by_agentcore_create: false
  supervisor_agent_2:
    name: supervisor_agent_2
    language: python
    node_version: '20'
    entrypoint: E:/AgentCore/agentcore_a2a/entrypoints/supervisor_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: podman
    source_path: E:\AgentCore
    aws:
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-733a737465
      execution_role_auto_create: false
      account: '948360714466'
      region: ap-south-1
      ecr_repository: 948360714466.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-supervisor_agent_2
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: supervisor_agent_2-mKa1CtEddC
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:948360714466:runtime/supervisor_agent_2-mKa1CtEddC
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-supervisor_agent_2-builder
      execution_role: arn:aws:iam::948360714466:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-733a737465
      source_bucket: bedrock-agentcore-codebuild-sources-948360714466-ap-south-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_myagent_memory-HPEmQF7XcU
      memory_arn: null
      memory_name: supervisor_agent_2_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: GROQ_API_KEY
    api_key_credential_provider_name: supervisor_agent_2_groq_api_key
    is_generated_by_agentcore_create: false
